version: '3.1'

services:

  db:
    image: postgres
    container_name: "article_postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./scripts/roles_table.sql:/docker-entrypoint-initdb.d/02-roles_table.sql
      - ./scripts/users_table.sql:/docker-entrypoint-initdb.d/03-users_table.sql
      - ./scripts/articles_table.sql:/docker-entrypoint-initdb.d/04-articles_table.sql
      - ./scripts/fill_tables.sql:/docker-entrypoint-initdb.d/05-fill_tables.sql

volumes:
  my_dbdata: