version: '3.1'

services:

  db:
    image: postgres
    container_name: "article_postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql

volumes:
  my_dbdata: